-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. RESUMES TABLE
create table resumes (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  file_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. JOBS TABLE
create table jobs (
  id uuid default uuid_generate_v4() primary key,
  normalized_url text not null,
  title text,
  company text,
  description text,
  skills text[], -- Added for skill extraction
  status text default 'collected',
  resume_used_id uuid references resumes(id),
  is_deleted boolean default false,
  source text,
  location text,
  salary text,
  posted_at text,
  work_type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Unique index to enforce duplicate prevention logic
-- We want uniqueness on normalized_url ONLY where is_deleted is false.
-- This allows re-saving a job if it was previously "deleted forever" (if hard delete) 
-- OR if we soft delete, maybe we want to block new adds and say "It's in trash"?
-- The spec says: "Query jobs where normalized_url = value AND is_deleted = false".
-- A partial unique index works best for this:
create unique index jobs_normalized_url_unique_idx on jobs (normalized_url) where (is_deleted = false);

-- 3. APP_CONFIG TABLE
create table app_config (
  id int primary key generated by default as identity,
  passcode_hash text not null
);

-- SECURITY (RLS)
-- Enable RLS
alter table resumes enable row level security;
alter table jobs enable row level security;
alter table app_config enable row level security;

-- Policies
-- Since we use Edge Functions with service_role for most operations (collect, unlock),
-- and web app uses a "session" that we might map to a custom claim or just check via middleware,
-- we need a basic policy to allow access. 
-- For simplicity in this "private single user" system, we'll allow access to anon for now 
-- BUT in production this should be tightened to only allow service_role or signed users.
-- However, spec says "Web App is source of truth... Extension checks session".
-- We will create a policy that allows all operations for now to unblock development, 
-- relying on the Application Layer (Edge Functions/Middleware) to handle the "Passcode Gate".

create policy "Allow all access for now" on jobs for all using (true) with check (true);
create policy "Allow all access for now" on resumes for all using (true) with check (true);
create policy "Allow all access for now" on app_config for all using (true) with check (true);

-- Functions associated (optional, if we want ID generation or triggers)

-- Enable Realtime for jobs table
alter publication supabase_realtime add table jobs;

-- Default Passcode: 123456
insert into app_config (passcode_hash) values ('123456');
